version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  aws-oidc:
    machine:
      image: ubuntu-2004:current
    steps:
      - aws-cli/assume-role-with-web-identity:
          role-arn: ${AWS_IAM_ROLE_ARN}

workflows:
  oidc:
    jobs:
      - aws-oidc:
          context: aws
